Metrics/LineLength:
  Description: Limit lines to 140 characters.
  Max: 140

Metrics/MethodLength:
  Description: Avoid methods longer than 20 lines of code.
  Max: 20

Metrics/AbcSize:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
